fact: fact.c
	gcc -o fact fact.c
array: array.c
	gcc -o array array.c	
pointer: pointer.c
	gcc -o pointer pointer.c
arraypointer: arraypointer.c
	gcc -o arraypointer arraypointer.c	
string: string.c
	gcc -o string string.c		
struct: struct.c
	gcc -o struct struct.c	
student: student.c
	gcc -o student student.c	
clean:
	rm fact array pointer arraypointer string struct
