fopen: fopen.c
	gcc -o fopen fopen.c
stcreate1: stcreate1.c
	gcc -o stcreate1 stcreate1.c
fsize: fsize.c
	gcc -o fsize fsize.c
copy: copy.c
	gcc -o copy copy.c
dup: dup.c
	gcc -o dup dup.c
dbcreate: dbcreate.c
	gcc -o dbcreate dbcreate.c
dbquery: dbquery.c
	gcc -o dbquery dbquery.c					
