cat: cat.c
	gcc -o cat cat.c
copy: copy.c
	gcc -o copy copy.c
line: line.c
	gcc -o line line.c
fprint: fprint.c
	gcc -o fprint fprint.c
fscan: fscan.c
	gcc -o fscan fscan.c
stcreate1: stcreate1.c
	gcc -o stcreate1 stcreate1.c
stprint: stprint.c
	gcc -o stprint stprint.c
stcreate2: stcreate2.c
	gcc -o stcreate2 stcreate2.c	
stquery: stquery.c
	gcc -o stquery stquery.c
stupdate: stupdate.c
	gcc -o stupdate stupdate.c								
